name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build and test
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      - run: npm run test:ci
      - run: npm run build
      - run: npm run build:demo
        env:
          CI: true
